apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment 
  labels:
    app: my-app 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: in28min/hello-world-python:0.0.2.RELEASE
        ports:
        - containerPort: 5000


---

apiVersion: v1 
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: LoadBalancer
